language: php

dist: trusty

php:
  - 7.0
  - 7.1
  - 7.2

env:
  global:
    - CC_TEST_REPORTER_ID=f116ce8b44aff91a5c70a5378f84af6e1511e99f5638bbf3446e11c12409d77e

before_script:
  - composer install
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

addons:
  sonarcloud:
    organization: "grgk-github"

script:
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml --log-junit build/logs/junit.xml --coverage-xml build/logs/coverage/xml --coverage-html build/logs/coverage/html
  - sonar-scanner

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
