language: php

dist: trusty

php:
  - 7.0
  - 7.1
  - 7.2

before_script:
  composer install

addons:
  sonarqube:
    token:
      secure: 6faf274296bd401caccc1db0304ed94803b42b84

script:
  - vendor/bin/phpunit --coverage-clover build/logs/phpunit/clover.xml --log-junit build/logs/phpunit/junit.xml --coverage-xml build/logs/phpunit/coverage/xml --coverage-html build/logs/phpunit/coverage/html
  - sonar-scanner
